### ISSUE TITLE
Support for PHP version 5.6

### ISSUE THREAD

**Issue by Swarlston** [plausible/wordpress#122]
Hi, I'm having trouble installing the versions 1.2.5 and 1.2.6 on a PHP 5.6 system.

It seems the releases force version 7.2 or higher.

I get an error message when trying to access my site after installing the plugin, that reads:
`Your Composer dependencies require a PHP version ">= 7.2.0". You are running 5.6.40`

This is caused by `vendor/composer/platform_check.php` in the ZIP-releases of 1.2.5 and 1.2.6.
I tried commenting out the responsible line, but that only fixed the error message and the site still didn't work.

I rolled back back to 1.2.4 which works just fine, but maybe you can help me update.

Thanks in advance.

**Comment by Dan0sz** [comment]
What's the reason you're still on PHP 5.6? 5.6 has been EOL for almost 5 years!

I'd seriously suggest upgrading to PHP 8. Or, at the very least 7.4 (which has also been EOL since the end of last year)

The new features introduced in 1.2.5 (and next up, 1.3.0) use functions only available in 7.2. Hence the raised requirements. We're not planning to keep supporting 5.6, simply because eventually WordPress will also drop its support.

But, if you must, since you're installing using Composer, have you tried to append `--ignore-platform-reqs` to the command?

**Comment by Dan0sz** [comment]
For anyone else interested, found this table, showing that PHP 5.6 support in WordPress is next up to be dropped:

![afbeelding](https://user-images.githubusercontent.com/18595395/235431867-634c0e6c-a6ff-4d6a-8c5a-e2666429dde6.png)

**Comment by Swarlston** [comment]
Thanks for the reply!
I'm afraid i can't upgrade the PHP installation.

I installed this plugin via the Wordpress dashboard, where it's marked as still 5.6 compatible in 1.2.5 and 1.2.6.
So when i tried to upgrade, it doesn't warn you and breaks the wordpress installation.

I'm not sure whether that's a problem on your end, just wanted to give you a heads-up.

Have a good one.

**Comment by Dan0sz** [comment]
Thanks for notifying me, I'll change that!
