### ISSUE TITLE
Not working anymore for selfhosted

### ISSUE THREAD

**Issue by ThomasTr** [plausible/wordpress#178]
After Upgrade to 2.0.2 from 1.3.6:
Analytics shows "Please enter your Shared Link under Self-Hosted Settings. 
This link is already set. Removed the domain and link, and setting it again also not helped.

Analytics script is also not injected anymore.

**Comment by ThomasTr** [comment]
Downgraded for now to version 1.3.6

**Comment by Dan0sz** [comment]
I can confirm this was a bug. I'm releasing 2.0.3 now, which includes the fix.

The wording was unfortunate, because as the code was written, the View Stats option (under General settings) also had to be enabled -- even when a Shared Link was entered under Self-Hosted settings.

So, the notice should've said: **Please enter your shared link under Self-Hosted Settings and enable View Stats under General settings.**

Because I figured this to be a bit too much of a hassle, as of 2.0.3 providing a shared link under Self-hosted settings will be enough.

**Comment by ThomasTr** [comment]
Thx for fast fix. Will try the new version when released.
