### ISSUE TITLE
Invalid handling of non-root home url

### ISSUE THREAD

**Issue by FlyingDR** [plausible/wordpress#199]
At this moment plugin incorrectly handles domain name extraction in case a non-root path is used as a home. `\Plausible\Analytics\WP\Helpers::get_domain()` for some reason tries to use a regular expression instead of using the standard `parse_url()` function:

https://github.com/plausible/wordpress/blob/18bc986f75baffe97fdf7868afce7193b0ef056e/src/Helpers.php#L261

Regular expression completely ignores the fact that there may be something after the domain name itself, effectively generating the wrong result. The most common scenario is use of the multilanguage plugins like WPML, see #160 for examples.

Since Plausible analytics [strictly expects hostname](https://plausible.io/docs/add-website#enter-the-domain-name-of-the-website-you-want-to-track) for the domain name it is currently not possible to use Plausible analytics for multilingual sites. Any registration attempt results in ["Oops! The API token you used is invalid"](https://github.com/plausible/wordpress/blob/18bc986f75baffe97fdf7868afce7193b0ef056e/src/Ajax.php#L314-L319) notification and attempt to use "create an API token" link causes issue because it takes invalid URL for Plausible because the value for domain is [taken from the form](https://github.com/plausible/wordpress/blob/18bc986f75baffe97fdf7868afce7193b0ef056e/assets/src/js/admin/main.js#L232-L235).

Correct implementation would be:

```php
return preg_replace('/^www\./i', '', parse_url($url, PHP_URL_HOST));
```

**Comment by Dan0sz** [comment]
Thanks for your thorough report!

I've investigated the issue, and the actual issue was that the API client would always use the hosted domain stored in the DB, resulting in the API token invalid error message. In [this commit](https://github.com/plausible/wordpress/commit/91148206c571b172e0d2df89a2e744728426ec9c) any submitted options in POST are grabbed when get_settings() is called.

Also, Plausible has supported domain names with a subdirectory structure (i.e. multilingual sites) for a while now. So parsing just the hostname is no longer needed.
