### ISSUE TITLE
Tracking issues with WP Rocket

### ISSUE THREAD

**Issue by ekirschner** [plausible/wordpress#39]
It seems that tracking is broken with WP Rocket and Plausible since the last update. Even with admin tracking enabled somehow the tracking code isn't visible in cached pages.

Could you please look into this issue?

**Comment by metmarkosaric** [comment]
sorry about that @ekirschner! there's the #38 already for more details and solutions on this topic. while we work on fixing the plugin, you can either:

1. deactivate WP Rocket and clear your cache or
2. manually whitelist Plausible script in WP Rocket settings or
3. use this Plausible snippet instead of our plugin:

`<script data-domain="website-domain.com" data-api='https://plausible.io/api/event' src="https://plausible.io/js/plausible.js"></script>`

**Comment by ekirschner** [comment]
Thanks for your feedback @metmarkosaric. For me only the combination of 2 and 3 worked out on most of my sites. I whitelisted the custom domains but still nothing happened with the plausible plugin. So I inserted the tracking code manually and now everything works fine.
