### ISSUE TITLE
Analytics dashboard not working with password protected shared links

### ISSUE THREAD

**Issue by maliev** [plausible/wordpress#98]

**Comment by maliev** [comment]
![Screenshot 2023-01-27 at 11 49 20](https://user-images.githubusercontent.com/76956279/215068614-38cd9467-a773-4739-be5d-c6635135d28b.png)

**Comment by metmarkosaric** [comment]
thanks for reporting this @maliev! yes, that's correct. it's impossible to embed a password protected shared link unfortunately due to technical reasons. please do keep the password field empty when creating a new shared link and it will work as an embed then. we have mentioned this on the different docs pages related to this feature so i'll close this
